#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

function die()
{
  >&2 echo "ERROR: $1"
  exit 1
}

function iw_scan()
{
 iw "$IF" scan           \
   | grep -i 'SSID'      \
   | head -30            \
   | cut -d: -f2         \
   | sed 's/^ //g'       \
   | grep -v 'SSID List' \
   | sort -u             \
   | fzf
}

[[ -n "$IF"  ]] || IF='wlan0'
[[ -n "$LOG" ]] || LOG='wpa_supplicant.log'
[[ -n "$DIR" ]] || DIR="$HOME/.iwpass"

ESSID="$*"

mkdir -p  "$DIR"
chmod 600 "$DIR"

[[ -z "$1"     ]] && ESSID="$(iw_scan)"
[[ -z "$ESSID" ]] && die "EMPTY SSID"

CONF="$DIR/$ESSID.conf"

if [[ ! -e "$CONF" ]]
then

  echo "NOT FOUND $CONF"

  PSK="$(pass "wifi/$ESSID/psk")"

  if [[ -z "$PSK" ]]
  then
    PASS="$(pass "wifi/$ESSID/pass")"
    PSK="$(pass "wifi/$ESSID/psk")"
    [[ -z "$PASS" ]] && die "NOT FOUND $PSK. TRY: pass insert wifi/$ESSID/pass"
    wpa_passphrase "$ESSID" "$PASS" > "$CONF"
  fi

CFG=$(cat << EOF
network={
        ssid="$ESSID"
        psk=$PSK
}
EOF
)

  echo "$CFG" > "$CONF"

fi

[[ ! -s "$CONF" ]] && die "EMPTY $CONF"

pkill -f wpa_supplicant
sleep 1
echo wpa_supplicant -i "$IF" -c "$CONF" -B -f "$LOG"
wpa_supplicant -i "$IF" -c "$CONF" -B -f "$LOG" || die "wpa_supplicant"
tail "$LOG"
sleep 2
tail "$LOG"
dhclient "$IF"
# FIXME rm -f "$CONF"
tail "$LOG"
ip r
