#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2001
# shellcheck disable=SC2005
# shellcheck disable=SC2181

[[ -e '.gpg-id' ]] || exit 1
[[ -n "$DIR"    ]] || DIR='.'
[[ -d "$DIR"    ]] || exit 1

export PASSWORD_STORE_DIR="$PWD"

find "$DIR" -type f -iname '*.gpg' \
  | grep '\.gpg$'                  \
  | cut -d/ -f2-                   \
  | while read -r F
    do
      [[ "$DIR" != '.' ]] && F="$DIR/$F"
      N="$(echo "$F" | sed 's/.gpg$//g')"
      DATA="$(gpg -d "$F" 2>/dev/null)"
      if [[ "$?" -eq 0 ]]
      then
        echo "$DATA" | pass insert "$N" -m
      else
        echo "ERROR $F" && continue
      fi
    done
